spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: false
      hibernate:
         ddl-auto: none
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: false
   datasource:
       type: com.zaxxer.hikari.HikariDataSource
       #dataSourceClassName: org.postgresql.Driver
       url: jdbc:postgresql://10.247.185.10:5432/soch_train_app_db?currentSchema=soch
       username: soch_train_app_user
       password: S0chApP2020
       hikari:
        poolName: Hikari

logging:
   level:
       root: error
       org: error
       gov: error
mhl:
  auth_key: c2285c7c4cdaf31f8486b35f171c643c
accessKey: devkey@3
crossDomainAllowedOrigins: https://sochtraining.naco.gov.in
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=