spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: false
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: false
         format_sql: true
      properties:
         hibernate.id.new_generator_mappings: true
         #hibernate.connection.provider_disables_autocommit: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: true
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      #dataSourceClassName: org.postgresql.Driver
      #url: jdbc:postgresql://localhost:9999/soch-db-dev?currentSchema=soch
      #url: jdbc:postgresql://13.127.180.228:9999/soch_db_dev_2?currentSchema=soch
      url: jdbc:postgresql://3.7.228.235:9999/soch_db_dev_2?currentSchema=soch
      username: postgres
      password: postgres
      hikari:
        poolName: Hikari
        #auto-commit: false
logging:
   level:
       root: ERROR
       org.springframework: ERROR
       com.naco.soch: ERROR
       org.hibernate: ERROR
mhl:
  auth_key: c2285c7c4cdaf31f8486b35f171c643c
accessKey: $5gw@965
crossDomainAllowedOrigins:
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=