spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: false
   datasource:
       dataSourceClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.247.185.10:5432/soch_train_app_db?currentSchema=soch
      username: soch_train_app_user
      password: S0chApP2020

logging:
   level:
       root: INFO
       org.springframework: INFO
       com.naco.soch: INFO
       org.hibernate: INFO
mhl:
  auth_key: c2285c7c4cdaf31f8486b35f171c643c
accessKey: $5gw@965
crossDomainAllowedOrigins:
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=