spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: false
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: false
         format_sql: true
   datasource:
      dataSourceClassName: org.postgresql.Driver
      url: jdbc:postgresql://13.232.7.148:5432/mig_db01?currentSchema=soch
      username: postgres
      password: postgres
logging:
   level:
       root: ERROR
       org.springframework: ERROR
       com.naco.soch: ERROR
       org.hibernate: ERROR